name: natus_gestantes
description: "Natus - gestão e relacionamento para clínicas"
publish_to: 'none'

version: 1.1.2+5

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mask_text_input_formatter: ^2.9.0
  file_picker: ^8.1.7
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  firebase_auth: ^6.0.0
  cloud_functions: ^6.2.0
  firebase_messaging: ^16.4.3
  url_launcher: ^6.3.2
  excel: ^4.0.6
  path_provider: ^2.1.5
  fl_chart: ^1.2.0
  google_maps_flutter: ^2.6.0
  geocoding: ^2.1.1
  http: ^1.2.0
  web: ^1.1.1
  firebase_app_check: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/frutas/
    - assets/Ramos/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon_app.png"
  min_sdk_android: 21
