// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3irHorITGhIAlxVYzgHewkGmI3eVQQMY',
    appId: '1:1078564037217:web:d630421cef24e5746f4020',
    messagingSenderId: '1078564037217',
    projectId: 'natus-gestantes',
    authDomain: 'natus-gestantes.firebaseapp.com',
    storageBucket: 'natus-gestantes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmVKa0rB1obPeNa-7SKaGDaZzI-WY_j4',
    appId: '1:1078564037217:android:a8730fbd791bfb686f4020',
    messagingSenderId: '1078564037217',
    projectId: 'natus-gestantes',
    storageBucket: 'natus-gestantes.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3D9lwpDaLbg2vEbjcS-Mmu9aIvx_5XRg',
    appId: '1:1078564037217:ios:15cbc04f0121b7736f4020',
    messagingSenderId: '1078564037217',
    projectId: 'natus-gestantes',
    storageBucket: 'natus-gestantes.firebasestorage.app',
    iosBundleId: 'com.example.natusGestantes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3D9lwpDaLbg2vEbjcS-Mmu9aIvx_5XRg',
    appId: '1:1078564037217:ios:15cbc04f0121b7736f4020',
    messagingSenderId: '1078564037217',
    projectId: 'natus-gestantes',
    storageBucket: 'natus-gestantes.firebasestorage.app',
    iosBundleId: 'com.example.natusGestantes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3irHorITGhIAlxVYzgHewkGmI3eVQQMY',
    appId: '1:1078564037217:web:31b4f0323bbeecb56f4020',
    messagingSenderId: '1078564037217',
    projectId: 'natus-gestantes',
    authDomain: 'natus-gestantes.firebaseapp.com',
    storageBucket: 'natus-gestantes.firebasestorage.app',
  );
}
